# -*- coding: utf-8 -*-
"""FINAL DT PROJECT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVbV9wsC3FHMrhbySZ8F1Pdiibz-dqCL
"""

# importing the required library
from imageai.Detection import ObjectDetection

# instantiating the class
detector = ObjectDetection()

# defining the paths
path_model = "/content/tiny-yolov3.pt"

# using the setModelTypeAsYOLOv3() function
detector.setModelTypeAsTinyYOLOv3()
# setting the path of the Model
detector.setModelPath(path_model)
# loading the model
detector.loadModel()
# calling the detectObjectsFromImage() function
detections = detector.detectObjectsFromImage(input_image="/content/high-park-1-6505124-1691080951454.jpg",
                                             output_image_path="/content/output.jpg",
                                             minimum_percentage_probability=30)
# iterating through the items found in the image
for eachItem in detections: #[{"name":"person","percentage_probability":100.0},{..},{..}]
    print(eachItem["name"] , " : ", eachItem["percentage_probability"])

!pip install cython pillow>=7.0.0 numpy>=1.18.1 opencv-python>=4.1.2 torch>=1.9.0 --extra-index-url https://download.pytorch.org/whl/cpu torchvision>=0.10.0 --extra-index-url https://download.pytorch.org/whl/cpu pytest==7.1.3 tqdm==4.64.1 scipy>=1.7.3 matplotlib>=3.4.3 mock==4.0.3
!pip install imageai --upgrade

